dotenv: .env
wallets:
  from_key: ${PRIVATE_KEY}

networks:
  rinkeby:
    eth_usd_price_feed: '0x8A753747A1Fa494EC906cE90E9f37563A8AF630e'
    verify: True
  developemnt:
    verify: False
  ganache-local:
    verify: False

dependencies:
#   - <organization/repo>@<version>
  - smartcontractkit/chainlink-brownie-contracts@0.3.1

compiler:
  solc:
    remappings:
      - '@chainlink=smartcontractkit/chainlink-brownie-contracts@0.3.1' 